### ISSUE TITLE
Example AsyncThunks

### ISSUE THREAD

**Issue by AntonyFagundez** [Codecademy/mock-react-redux#34]
Hi first of all thanks for the library! It make it easy the mock of redux!

I'm looking for examples to implement an async actions  but without success.

It's posible with the current implementation, make tests for async thunk actions?

I've tryed with the [Examples](https://github.com/Codecademy/mock-react-redux/tree/08931013f2302ba6e391c53bb9a1bc702c0bd608/docs/examples) but without success.

I'm trying with the current code (importing original async action)

``` jsx
test("Should dispatch if all fields exists and were validated", async () => {
    const { dispatch } = mockReactRedux();

    const mockedSubmit = jest.fn().mockImplementation(() => {
      dispatch(newContact(values));
    });

    render(<ContactForm onSubmit={mockedSubmit} />);

    userEvent.type(screen.getByPlaceholderText("Nombre"), "John");
    userEvent.type(screen.getByPlaceholderText("Email"), "john@gmail.com");
    userEvent.type(screen.getByPlaceholderText("Teléfono"), "23456789");
    userEvent.type(screen.getByPlaceholderText("Escribe tu mensaje"), "Lorem ipsum dolor sit");

    userEvent.click(screen.getByTestId("contactButton"));

    await waitFor(() => {
      expect(dispatch).toHaveBeenCalled();
      expect(dispatch).toHaveBeenCalledWith(newContact(values));
    });
  });

```

But the result is:
![image](https://user-images.githubusercontent.com/47680399/155327207-8b2feef9-0771-4784-8abc-2671e36787ec.png)

I think maybe is for the thunk middleware.

PD: Sorry if my english is not good, I'm still learning!

Best Regards!

**Comment by JoshuaKGoldberg** [comment]
Hi @AntonyFagundez, thanks for the issue! Totally clear & understandable English; what you're asking for makes sense.

This is an annoying quirk we found around working with dispatched thunks, yeah. I'm guessing your `newContact` function looks something like:

```ts
export const newContact = (values) => (dispatch, getState) => {
  /* ... */
};
```

```ts
expect(dispatch).toHaveBeenCalledWith(newContact(values)); // New function ❌
```

Structure like that means `newContact` returns a new `[Function anonymous]` every time it's called. I'll add an example to the docs.

In the meantime...

## Strategy: Same Function

One solution would be to make a function that stays the same between them:

```ts
export const newContentThunk = (dispatch, getState) => {
  /* ... */
};

export const newContent = () => newContentThunk;
```

```ts
expect(dispatch).toHaveBeenCalledWith(newContentThunk()); // Same function ✔
```

...though that direct line of code doesn't support an action prop the way your `newContact` takes in a `values`.

## Strategy: Memoized Function

If you want to support parameters, you could use something like [Lodash's memoize](https://lodash.com/docs/4.17.15#memoize) to cache the function returned by `newContent`:

```ts
import { memoize } from "lodash";

export const newContent = memoize((values) => {
  return (dispatch, getState) => {
    /* ... */
  };
});
```

```ts
const values = {
  /* ... */
};

newContent(values);

expect(dispatch).toHaveBeenCalledWith(newContent(values)); // Same function ✔
```

Note that Lodash by default does a strict equality check, so while the above snippet works, `newContent({}) === newContent({})` would result in `false` because the `{}` is different between those two calls.

**Comment by AntonyFagundez** [comment]
Hi @JoshuaKGoldberg thanks for the detailed answer>

I was indeed making a mistake comparing two references in memory. 

With your help I finally get a solution (with `memoize` from `lodash`)

```jsx

  test("Should dispatch if all fields exists and were validated", async () => {
    const { dispatch, state } = mockReactRedux();

    const sameFunction = memoize(() => newContact(values)(dispatch, state));

    const mockedSubmit = jest.fn().mockImplementation(() => {
      dispatch(sameFunction());
    });

    render(<ContactForm onSubmit={mockedSubmit} />);

    userEvent.type(screen.getByPlaceholderText("Nombre"), "John");
    userEvent.type(screen.getByPlaceholderText("Email"), "john@gmail.com");
    userEvent.type(screen.getByPlaceholderText("Teléfono"), "23456789");
    userEvent.type(screen.getByPlaceholderText("Escribe tu mensaje"), "Lorem ipsum dolor sit");

    userEvent.click(screen.getByTestId("contactButton"));

    await waitFor(() => {
      expect(dispatch).toHaveBeenCalled();
      expect(dispatch).toHaveBeenCalledWith(sameFunction());
    });
  });
```


Thanks again!!
